// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import LoadingScreen from "@/modules/shared/LoadingScreen/ui/LoadingScreen";
import "@/styles/globals.css";
// import { Providers } from "@/modules/app";
import { Footer } from "@/modules/widgetes";
import { Header } from "@/modules/admin";
import { Sidebar } from "@/modules/widgetes";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Admin",
//   description: "Generated by create next app",
// };

export default function NetworkLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <div className="">
      <LoadingScreen />

      <div className="w-full z-10">
        <Header type="network" />
      </div>
      <div className="min-w-full min-h-screen bg-mainLightBackground">
        <div className="container px-6 sm:px-0 max-w-6xl mx-auto min-h-screen flex flex-row ">
          <Sidebar />
          <main className="w-full">
            {children}

          </main>
        </div>

        <Footer />
      </div>
    </div>
  );
}

